### ISSUE TITLE
app.use() requires middleware functions

### ISSUE THREAD

**Issue by CrackerakiUA** [expressjs/method-override#10]
After your last update on news projects i detect this error. Actually this error first show on express/lib/application.js:209:11 but later on our server file it shows on app.use(methodOverride('X-HTTP-Method-Override')); line.

**Comment by dougwilson** [comment]
Hi! I'm really sorry, I'm not following what the issue is. Do you think you could issue a PR to us that fixes the issue for you?

**Comment by CrackerakiUA** [comment]
![screenshot 2015-07-23 19 48 47](https://cloud.githubusercontent.com/assets/6815721/8856575/530e4306-3174-11e5-9baf-4dad08198965.png)
Here is the error, also the exactly same error is on multer middleware, should i create a issues on they github?

**Comment by dougwilson** [comment]
Hi! So using the single line of code you provided and the latest version of this module and express, I could not reproduce for whatever reason. This, unfortunately, means we probably cannot do anything without you providing a PR with a fix :(

**Comment by CrackerakiUA** [comment]
ok, i tested it deeper and found that multer is the problem, not method-override. So i close the issue here. Also small question, where i can find pr of that error, so i put it into issues of multer?

**Comment by dougwilson** [comment]
> where i can find pr of that error, so i put it into issues of multer?

That error has been in Express for so long (at least a year now), that it's hard to even know what the PR is, if there was even a PR that added it at all (anything added by core committers is not done as a PR).
